services:
  valheim:
    image: ghcr.io/community-valheim-tools/valheim-server
    cap_add:
      - sys_nice
    volumes:
      - ./valheim-server/config:/config
      - ./valheim-server/data:/opt/valheim
    ports:
      - "2456-2458:2456-2458/udp" # Game
      - "9001:9001/tcp" # Supervisor
      - "8080:80/tcp" # Status
    env_file:
      - ./valheim.env
    restart: always
    stop_grace_period: 2m
